### ISSUE TITLE
HTML icon missing

### ISSUE THREAD

**Issue by LOQUILLO** [wesbos/cobalt2#22]
Hi @wesbos the icon for HTML or htm files is missing:
![html_bug](https://cloud.githubusercontent.com/assets/1308190/4873296/57dd94c4-620b-11e4-9de2-0811601b0484.png)

ST3 Dev Build 3066
Windows 7 x64

**Comment by jedateach** [comment]
@wesbos is it possible to define icons for file types in preferences? Eg, I have html template files, ending with an extension ".ss", which currently shows the RSS icon, and I would prefer it to be the ".html" icon.

**Comment by wesbos** [comment]
@jedateach What is .ss? You could easily add a second definition but if it's a standard format I'm happy to add it

**Comment by jedateach** [comment]
Its the template format the SilverStripe PHP CMS/framework's templating engine. I'm not sure if thats common enough. How do you add definitions?

**Comment by wesbos** [comment]
Create a new file that looks like this:
https://github.com/wesbos/cobalt2/blob/master/prefs/icon_html.tmPreferences

but replace `text.html.basic` with `source.ss` 

You might be able to get away with two `<dict>` tags in the HTML file as well

**Comment by jedateach** [comment]
Thanks @wesbos.

It looks like it'll require more than just adding a file on disk. I'm guessing some build process is needs to be on the cobalt2 repo. Disclaimer: I've never done theme work in Sublime.

**Comment by jedateach** [comment]
@wesbos I've learned that I can make customisations by cloning into Packages.

I couldn't get things to work by adding a new tmPreferences file. Can you point me to any docs on how the icons system works + how to configure it?

Otherwise, my mid-term workaround is to replace the 'markup' (rss) icon with a different one. Its strange that this icon is being defaulted to for whatever reason.
